.
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppewunzbgjxiybfjzghf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwZXd1bnpiZ2p4aXliZmp6Z2hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwODY5MDEsImV4cCI6MjA1NjY2MjkwMX0.TWHgkTg_RvdckS93A0x9tFv_TGXV9EKTYCOrbt5Oax8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add these type declarations to help with the community messages table
// until the generated types are updated
declare module '@supabase/supabase-js' {
  interface PostgrestQueryBuilder<Schema> {
    community_messages?: any;
  }
}
